---
version: 2.1
jobs:
  build:
    working_directory: ~/serverless-iiif
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - node-modules-v1-{{ checksum "yarn.lock" }}-
            - node-modules-v1-
      - run:
          name:  Download cc-test-reporter
          command: |
            curl -L -o ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
            chmod +x ./cc-test-reporter
      - run:
          name: Install JS Dependencies
          command: yarn install
      - save_cache:
          key: node-modules-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - ~/serverless-iiif/node_modules
      - run:
          name: JS Tests
          command: |
            ./cc-test-reporter before-build
            yarn test --coverage
            mv coverage/clover.xml ./clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
      - run:
          name: Send coverage to Coveralls
          command: yarn run coveralls < coverage/lcov.info
